name: sms_app
description: SMS Listener with background video and sound
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  telephony: ^0.2.0
  http: ^1.1.0
  video_player: ^2.7.0
  audioplayers: ^5.2.0
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
