name: Flutter Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Create Flutter Android Project
        run: |
          flutter create -t app temp_flutter_app
          cp -r lib pubspec.yaml temp_flutter_app/
          cd temp_flutter_app
          flutter pub get

      - name: Add Android Permissions
        run: |
          FILE="temp_flutter_app/android/app/src/main/AndroidManifest.xml"
          sed -i '/<manifest/a \
      <uses-permission android:name="android.permission.INTERNET" /> \
      <uses-permission android:name="android.permission.READ_SMS" /> \
      <uses-permission android:name="android.permission.RECEIVE_SMS" /> \
      <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />' "$FILE"
        shell: bash
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.22.0-x64
          PUB_CACHE: /home/runner/.pub-cache

      - name: Build APK
        run: |
          cd temp_flutter_app
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: temp_flutter_app/build/app/outputs/flutter-apk/app-release.apk
